name: Linting

on:
  push:
    branches:
      - master
    tags-ignore: ["**"]
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write
  security-events: write

jobs: # Docs: <https://git.io/JvxXE>
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with: {fetch-depth: 0}

      - uses: gacts/gitleaks@beadb7dfb484e933cf3e29e2b589f7d42699c4b1 # v1.2.2 # Action page: <https://github.com/zricethezav/gitleaks-action>
        with:
          config-path: .gitleaks.toml
